server:
  port: 8085
spring:
  application:
    name: flight-auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/flight_auth_db
    username:
    password:
    driver-class-name:

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

      flyway:
        enabled: true

logging:
  level:
    org.hibernate.SQL: INFO
    org.learnjava: INFO