server:
  port: 8085

spring:
  application:
    name: flight-auth-service


services:
  user-service:
    base-url: http://localhost:8082

internal:
  token: ${INTERNAL_SERVICE_TOKEN}


application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}



logging:
  level:
    org.learnjava: INFO
