server:
  port: 8085

spring:
  application:
    name: flight-auth-service


services:
  user-service:
    base-url: http://localhost:8082

internal:
  token: ${INTERNAL_SERVICE_TOKEN:dev-internal-token}


application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}



logging:
  level:
    org.learnjava: INFO
