server:
  port: 8080

spring:
  application:
    name: flight-gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id : flight-auth-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/auth/**

            - id: block-user-internal-endpoints
              uri: no://op
              predicates:
                - Path=/api/v1/users/internal/**
              filters:
                - name: SetStatus
                  args:
                    status: NOT_FOUND

            - id: flight-user-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/users/**

            - id: flight-booking-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/bookings/**
management:
  endpoints:
    web:
      exposure:
        include: health,info


application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}